### ISSUE TITLE
Form button has wrong color for dark scheme

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-boilerplate#34]

**Comment by SSirjes** [comment]
In preview mode form submit button is not good readable:
![screen shot 2015-11-16 at 15 10 54](https://cloud.githubusercontent.com/assets/13623224/11182573/63733af2-8c74-11e5-88e7-76d01355951d.png)

In edit mode form submit text is readable:
![screen shot 2015-11-16 at 15 13 30](https://cloud.githubusercontent.com/assets/13623224/11182603/a0b451ee-8c74-11e5-8d0f-3ae42bc8cbf5.png)
