### ISSUE TITLE
Line height for H1 tag is too small

### ISSUE THREAD

**Issue by tanelj** [Voog/design-boilerplate#40]
![pripjat-h1-line-height](https://cloud.githubusercontent.com/assets/378755/11145723/e5a9ea5e-8a10-11e5-9eae-bfd47146bb77.png)

**Comment by SSirjes** [comment]
H1 need some line-height (for example 122px)
![screen shot 2015-11-13 at 15 33 19](https://cloud.githubusercontent.com/assets/13623224/11147042/e3d05906-8a1b-11e5-9926-ff4da4d5a5e3.png)
