### ISSUE TITLE
Mobile view: on 506px disappears search box

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-boilerplate#42]
![screen shot 2015-11-13 at 15 52 11](https://cloud.githubusercontent.com/assets/13623224/11147435/8736fc4c-8a1e-11e5-953c-fd68f4077943.png)

..507px, with search
![screen shot 2015-11-13 at 15 52 42](https://cloud.githubusercontent.com/assets/13623224/11147447/a5858538-8a1e-11e5-8acd-1bef59b27e4f.png)

**Comment by kaspar-naaber** [comment]
Removed the code that hides search from mobile views. The positioning of the search modal will update with a CMS update that improves search plugin.

Boilerplate v2 will have better styling and positioning for the search.
