### ISSUE TITLE
Front page: content title changes color and is not editable in mobile view

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-boilerplate#46]
Desktop:
![screen shot 2015-11-16 at 13 27 52](https://cloud.githubusercontent.com/assets/13623224/11180765/0651f466-8c66-11e5-816e-4178ed21f1e9.png)

Mobile:
![screen shot 2015-11-16 at 13 28 07](https://cloud.githubusercontent.com/assets/13623224/11180766/066b6f40-8c66-11e5-8511-4e26e8792843.png)

**Comment by kaspar-naaber** [comment]
Will be fixed in v2.
