### ISSUE TITLE
Fix flags sprite map

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-boilerplate#6]
British, Australian and Czech flags are broken.

![screen shot 2014-10-30 at 11 58 34](https://cloud.githubusercontent.com/assets/3191867/4841510/5eaf00c2-601b-11e4-95e9-edf48c3fcf3e.png)

![screen shot 2014-10-30 at 11 58 37](https://cloud.githubusercontent.com/assets/3191867/4841512/61598d10-601b-11e4-8eb7-6aae025bdeb4.png)

![screen shot 2014-10-30 at 11 58 30](https://cloud.githubusercontent.com/assets/3191867/4841515/64ff86c2-601b-11e4-9cbe-06d6f17a9228.png)

**Comment by runnel** [comment]
Probleem laheneb, kui sa ei optimeeri nüüd seda faili täiendavalt. Võimalik et grunt või miski lööb siit olulisi komponente välja. Saadan faili Slackis.

**Comment by kaspar-naaber** [comment]
Fixed.
